import {notFound} from 'next/navigation';
import Link from 'next/link';
import {getGuides} from '@/lib/content';
import {metadata,site} from '@/lib/site';
import {software} from '@/data/software';
import {Breadcrumb,Toc,AdSlot,Disclosure,JsonLd} from '@/components/ui';
import {GuideContent} from '@/components/guide-content';
export function generateStaticParams(){return getGuides().map(g=>({slug:g.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const g=getGuides().find(g=>g.slug===slug);return g?{...metadata(g.title,g.description,`/guides/${slug}`),openGraph:{type:'article' as const,title:g.title,description:g.description,url:`/guides/${slug}`,publishedTime:g.publishedAt,modifiedTime:g.updatedAt}}:{};}
export default async function Guide({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const g=getGuides().find(g=>g.slug===slug);if(!g)notFound();const headings=Array.from(g.content.matchAll(/^## (.+)$/gm),m=>m[1]);const formatDate=(date:string)=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(date));return <div className="page-content"><Breadcrumb items={[{label:'Guides',href:'/guides'},{label:g.title}]}/><header className="article-header"><span className="eyebrow">{g.category}</span><h1>{g.title}</h1><p className="deck">{g.description}</p><div className="article-byline"><span className="avatar">SS</span><span>By <Link href="/about">{g.author}</Link><small>Published <time dateTime={g.publishedAt}>{formatDate(g.publishedAt)}</time> <span>·</span> Updated <time dateTime={g.updatedAt}>{formatDate(g.updatedAt)}</time> <span>·</span> {g.readingTime} min read</small></span></div>{g.affiliate&&<Disclosure/>}</header><div className="reading-layout"><article className="prose"><AdSlot placement="below introduction"/><GuideContent content={g.content}/><AdSlot placement="article end"/><div className="article-end"><span className="eyebrow">KEEP EXPLORING</span><h3>A better shortlist starts with better questions.</h3><Link className="text-link" href="/software">Explore the software directory →</Link></div></article><aside className="reading-sidebar"><Toc headings={headings}/><div className="related-sidebar"><span className="eyebrow">RELATED SOFTWARE</span>{software.filter(s=>g.softwareMentioned.includes(s.slug)).map(s=><Link key={s.slug} href={s.reviewUrl}>{s.name}<small>Sample research profile ↗</small></Link>)}{g.softwareMentioned.length===0&&<Link href="/software">Browse software by category →</Link>}</div><AdSlot placement="sidebar"/></aside></div><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:g.title,description:g.description,datePublished:g.publishedAt,dateModified:g.updatedAt,author:{'@type':'Person',name:g.author,url:`${site.url}/about/`},publisher:{'@type':'Organization',name:site.name,url:site.url},mainEntityOfPage:`${site.url}/guides/${slug}/`}}/><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{name:'Home',url:site.url},{name:'Guides',url:`${site.url}/guides/`},{name:g.title,url:`${site.url}/guides/${slug}/`}].map((v,i)=>({'@type':'ListItem',position:i+1,name:v.name,item:v.url}))}}/></div>;}

