import {notFound} from 'next/navigation';
import Link from 'next/link';
import {propertyTypes,slugify} from '@/data/software';
import {PageIntro,Breadcrumb,Callout} from '@/components/ui';
import {metadata} from '@/lib/site';
const priorities:Record<string,string[]>={'Small Hotel':['A shared arrivals and departures view','Room-type inventory and rate plans','A dependable housekeeping handoff'],'Boutique Hotel':['Personal guest context and communication','Room differences and special requests','A direct-booking journey that reflects your property'],Guesthouse:['A simple calendar everyone can trust','Clear arrival instructions','Low training effort and predictable costs'],Villa:['Unit-level availability and minimum stays','Deposits, balances and cancellation terms','Cleaning and access between stays'],'Vacation Rental':['Channel mapping and reservation changes','Guest messages with human oversight','Turnover tasks and payment visibility'],'Property Manager':['Permissions across owners and staff','Multi-location inventory and reporting','Clear escalation for exceptions']};
export function generateStaticParams(){return propertyTypes.map(p=>({slug:slugify(p)}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=propertyTypes.find(p=>slugify(p)===slug);return p?metadata(`${p} software playbook`,`Build a hospitality software shortlist around ${p.toLowerCase()} operations.`,`/property-types/${slug}`):{};}
export default async function Property({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=propertyTypes.find(p=>slugify(p)===slug);if(!p)notFound();return <div className="page-content"><Breadcrumb items={[{label:'Software',href:'/software'},{label:p}]}/><PageIntro eyebrow="YOUR PROPERTY PLAYBOOK" title={`A better stack for your ${p.toLowerCase()}.`}>Start with the work your team actually does. Then choose tools that make it easier.</PageIntro><div className="prose narrow"><h2>Three priorities to take into a demo</h2><ol>{priorities[p].map(v=><li key={v}>{v}</li>)}</ol><h2>Build the foundation first</h2><p>Map the path from a new reservation to a ready room. Establish where your inventory lives, how channels update it and who handles a change. Add specialist tools when you can describe the specific task they will improve.</p><Callout title="A PLANNING GUIDE, NOT A VENDOR RANKING">This playbook offers general evaluation questions. It does not recommend a product or assume a particular vendor has been tested.</Callout><h2>A sensible evaluation order</h2><ol><li><Link href="/software/#pms">Reservation and property management</Link></li><li><Link href="/software/#channel-managers">Channel management and inventory sync</Link></li><li><Link href="/software/#booking-engines">Your direct-booking journey</Link></li><li><Link href="/software/#guest-messaging">Guest communication and team handoffs</Link></li></ol><h2>Make your shortlist measurable</h2><p>Record your room or unit count, sales channels, staff roles, country and payment currency. Ask each vendor to demonstrate the same three workflows with that context. Compare the full cost, migration work and data-export options.</p><Link className="button" href="/software">Explore software →</Link></div></div>;}
