'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { Logo, Arrow } from './ui';
export interface SearchItem {title:string;description:string;href:string;type:string;}
export function Header({items}:{items:SearchItem[]}) {const [menu,setMenu]=useState(false);const [query,setQuery]=useState('');const dialog=useRef<HTMLDialogElement>(null); const input=useRef<HTMLInputElement>(null); const path=usePathname();
function openSearch(){dialog.current?.showModal();input.current?.focus();}
function closeSearch(){dialog.current?.close();setQuery('');}
useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();dialog.current?.showModal();input.current?.focus();}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
const results=items.filter(i=>`${i.title} ${i.description} ${i.type}`.toLowerCase().includes(query.toLowerCase().trim()));
return <><header className="site-header"><Link href="/" aria-label="InnStack home"><Logo/></Link><nav className={menu?'main-nav is-open':'main-nav'} aria-label="Main navigation">{['Software','Comparisons','Guides','Tools','About'].map(n=><Link onClick={()=>setMenu(false)} key={n} aria-current={path.startsWith('/'+n.toLowerCase())?'page':undefined} href={'/'+n.toLowerCase()}>{n}</Link>)}</nav><div className="header-actions"><button className="search-trigger" aria-label="Search InnStack" onClick={openSearch}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/></svg><span>Search</span><kbd>⌘ K</kbd></button><Link className="button header-cta" href="/software">Find software <Arrow/></Link><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'✕':'☰'}</button></div></header><dialog ref={dialog} className="search-dialog" onClick={e=>{if(e.target===dialog.current)closeSearch();}}><div className="search-inner"><div className="search-top"><label htmlFor="site-search">Search the field guide</label><button aria-label="Close search" onClick={closeSearch}>✕</button></div><input ref={input} id="site-search" type="search" placeholder="Try ‘channel manager’ or ‘Lodgify’" value={query} onChange={e=>setQuery(e.target.value)}/><p className="muted" role="status">{results.length} {results.length===1?'result':'results'} · software, guides & comparisons</p><div className="search-results">{results.map(i=><Link key={i.href} href={i.href} onClick={()=>{closeSearch();setMenu(false);}}><span className="eyebrow muted">{i.type}</span><h3>{i.title} <Arrow/></h3><p>{i.description}</p></Link>)}{results.length===0&&<p>No matches yet. Try a category such as booking, PMS or software.</p>}</div></div></dialog></>;}
