import Link from 'next/link';
import {categories,propertyTypes,slugify} from '@/data/software';
import {getGuides} from '@/lib/content';
import {Architecture} from './architecture';
import {Arrow,SectionTitle} from './ui';
export function Hero(){return <><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="olive-dot"/> INDEPENDENT HOSPITALITY. INFORMED CHOICES.</div><h1>Better software.<br/><em>Better hospitality.</em></h1><p>Less time figuring out technology.<br/>More time looking after your guests.</p><p className="hero-description">Independent guides to help hotels, villas and vacation-rental operators choose the tools behind a better business.</p><div className="hero-actions"><Link href="/software" className="button">Explore software <Arrow/></Link><Link href="/comparisons" className="text-link">View comparisons <Arrow/></Link></div><div className="hero-footnote"><span>INDEPENDENT BY DESIGN</span><span className="tiny-line"/>Built around your property, not a sales pitch.</div></div><Architecture/></section><div className="audience-strip"><span>FOR THE INDEPENDENT IN HOSPITALITY</span><span>Small hotels</span><i>·</i><span>Boutique stays</span><i>·</i><span>Villas & guesthouses</span><i>·</i><span>Vacation rentals</span></div></>;}
export function CategorySection(){return <section className="section"><SectionTitle number="01" title="Find the right tools for your day-to-day." href="/software" label="All software categories"/><div className="category-grid">{categories.slice(0,8).map(([id,name,desc,icon])=><Link className="category-item" href={`/software/#${id}`} key={id}><span className="category-icon" aria-hidden="true">{icon}</span><div><h3>{name} <Arrow diagonal/></h3><p>{desc}</p></div></Link>)}</div></section>;}
export function FeaturedComparison(){return <section className="featured-comparison"><div className="comparison-art"><div className="eyebrow">A CLOSER LOOK</div><div className="versus-art"><div><span className="product-mark lodgify">L</span><strong>Lodgify</strong></div><span className="vs">vs.</span><div><span className="product-mark hostaway">H</span><strong>Hostaway</strong></div></div><div className="comparison-art-bottom">TWO PLATFORMS. DIFFERENT PRIORITIES.</div></div><div className="featured-copy"><span className="eyebrow">FEATURED COMPARISON <span className="sample-label">SAMPLE</span></span><h2>Lodgify vs Hostaway.<br/><em>Which fits your kind of business?</em></h2><p>A good comparison starts with how you work. Explore a framework for weighing direct bookings, daily operations and a growing portfolio.</p><div className="tags"><span className="tag">Independent hosts</span><span className="tag">Small property managers</span></div><Link className="text-link" href="/comparisons/lodgify-vs-hostaway">Explore the comparison <Arrow/></Link></div></section>;}
export function LatestGuides(){return <section className="section"><SectionTitle number="02" title="A little clarity goes a long way." href="/guides" label="Browse the guides"/><div className="guide-grid">{getGuides().map((g,i)=><Link className="guide-preview" href={`/guides/${g.slug}`} key={g.slug}><div className={`guide-visual guide-visual-${i}`} aria-hidden="true">{i===0?<><span className="mini-channel">Booking channels</span><span className="connection">↓ &nbsp; ↓ &nbsp; ↓</span><span className="mini-pms">One shared calendar</span><span className="connection">↓</span><span className="mini-channel">A room for every guest.</span></>:i===1?<><span className="editorial-symbol">⌂ <i>+</i> ⇄</span><span>OPERATIONS MEETS DISTRIBUTION</span></>:<><span className="stack-line">01 <b>Your property</b></span><span className="stack-line">02 <b>Your workflow</b></span><span className="stack-line">03 <b>Your software</b></span></>}</div><div className="guide-meta"><span>{g.category}</span><span>{g.readingTime} MIN READ</span></div><h3>{g.title}</h3><p>{g.description}</p><span className="text-link">Read guide <Arrow/></span></Link>)}</div></section>;}
export function PropertySection(){return <section className="property-section"><div><span className="eyebrow">03 / YOUR PROPERTY. YOUR PRIORITIES.</span><h2>A six-room guesthouse<br/>isn’t a sixty-room hotel.</h2><p>Your software stack should know the difference.<br/>Start with the kind of hospitality business you run.</p><Link href="/software" className="text-link">Find your hospitality stack <Arrow/></Link></div><div className="property-links">{propertyTypes.map((p,i)=><Link href={`/property-types/${slugify(p)}`} key={p}><span className="property-number">0{i+1}</span>{p}<Arrow diagonal/></Link>)}</div></section>;}
export function ToolsSection(){return <section className="section"><SectionTitle number="04" title="Good decisions start with the numbers." href="/tools" label="All free tools"/><div className="home-tools"><Link href="/tools/ota-commission-calculator"><span className="tool-icon" aria-hidden="true">%</span><div><span className="eyebrow muted">THE COST OF DISTRIBUTION</span><h3>OTA Commission Calculator</h3><p>See what your bookings really cost.</p></div><Arrow/></Link><Link href="/tools/direct-booking-savings-calculator"><span className="tool-icon" aria-hidden="true">↗</span><div><span className="eyebrow muted">THE VALUE OF GOING DIRECT</span><h3>Direct Booking Savings</h3><p>Explore what a different booking mix could mean.</p></div><Arrow/></Link></div></section>;}
