import Image from 'next/image';
import Link from 'next/link';
import type { ReactNode } from 'react';
import { slugify, type Software } from '@/data/software';
export function Logo() { return <span className="logo"><svg width="27" height="33" viewBox="0 0 32 38" aria-hidden="true"><path d="M3 35V17a13 13 0 0 1 26 0v18M10 35V17a6 6 0 0 1 12 0v18M0 35h32" fill="none" stroke="currentColor" strokeWidth="2"/></svg>InnStack<span className="logo-dot">.</span></span>; }
export function Arrow({ diagonal=false }: { diagonal?: boolean }) { return <span aria-hidden="true">{diagonal?'↗':'→'}</span>; }
export function SectionTitle({number,title,href,label='Explore all'}:{number:string;title:string;href?:string;label?:string}) { return <div className="section-heading"><div><span className="eyebrow muted">{number} / THE INNSTACK FIELD GUIDE</span><h2>{title}</h2></div>{href&&<Link className="text-link" href={href}>{label} <Arrow/></Link>}</div>; }
export function PageIntro({eyebrow,title,children}:{eyebrow:string;title:string;children:ReactNode}) {return <header className="page-intro"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><div className="deck">{children}</div></header>;}
export function SampleNotice(){return <div className="sample-note"><span aria-hidden="true">◈</span><p><strong>Sample research content.</strong> This illustrates our publishing format. It is not a tested review, verified feature list or product recommendation. Confirm current details with each vendor.</p></div>;}
export function Disclosure(){return <p className="disclosure">InnStack may earn a commission when you purchase through some links on this page. This does not affect what you pay.</p>;}
export function AffiliateButton({product,href,label='Visit official website',tracking,affiliate=false}:{product:string;href:string;label?:string;tracking?:string;affiliate?:boolean}) {return <div><a className="button" href={href} target="_blank" rel={affiliate?'sponsored nofollow noopener noreferrer':'noopener noreferrer'} data-product={product} data-tracking={tracking}>{label} <Arrow diagonal/></a>{affiliate&&<Disclosure/>}</div>;}
export function TestedBadge({tested}:{tested:boolean}){return tested?<span className="tag">✓ InnStack Tested</span>:null;}
export function AdSlot({placement}:{placement:string}){return process.env.NODE_ENV==='development'?<aside className="ad-slot" aria-label="Development advertising placeholder">AD PLACEMENT · {placement} · DEVELOPMENT ONLY</aside>:null;}
export function Callout({title='Worth knowing',children,kind='tip'}:{title?:string;children:ReactNode;kind?:'tip'|'warning'}) {return <aside className={`callout ${kind}`}><span className="eyebrow">{title}</span><div>{children}</div></aside>;}
export function InnStackTip({children}:{children:ReactNode}) {return <Callout title="InnStack Tip">{children}</Callout>;}
export function PropertyExample({title,children}:{title:string;children:ReactNode}) {return <section className="property-example" id={slugify(title)}><span className="eyebrow">PROPERTY EXAMPLE</span><h2>{title}</h2><div>{children}</div></section>;}
export function FAQ({items}:{items:{question:string;answer:string}[]}){return <div className="faq">{items.map(i=><details key={i.question}><summary>{i.question}<span aria-hidden="true">+</span></summary><p>{i.answer}</p></details>)}</div>;}
export function ProsCons({pros,cons}:{pros:string[];cons:string[]}){return <div className="pros-cons">{[['Potential advantages',pros],['Questions to resolve',cons]].map(([title,items])=><div key={title as string}><h3>{title as string}</h3><ul>{(items as string[]).map(s=><li key={s}>{s}</li>)}</ul></div>)}</div>;}
export function SoftwareCard({product}:{product:Software}){return <Link className="software-card" href={product.reviewUrl}><span className={`product-mark ${product.slug}`}>{product.name[0]}</span><div><h3>{product.name} <Arrow diagonal/></h3><p>{product.description}</p><span className="eyebrow muted">RESEARCH PROFILE · {product.propertySize.join(' / ')}</span></div></Link>;}
export function Screenshot({src,alt,caption}:{src:string;alt:string;caption?:string}){return <figure className="screenshot"><Image src={src} alt={alt} width={1200} height={750} sizes="(max-width: 850px) 100vw, 740px"/>{caption&&<figcaption>{caption}</figcaption>}</figure>;}
export function ComparisonTable({headers,rows}:{headers:string[];rows:string[][]}){return <div className="table-scroll" tabIndex={0} role="region" aria-label="Comparison table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=>j===0?<th scope="row" key={j}>{v}</th>:<td key={j}>{v}</td>)}</tr>)}</tbody></table></div>;}
export function Toc({headings}:{headings:string[]}){return <nav className="toc" aria-label="On this page"><span className="eyebrow">IN THIS GUIDE</span>{headings.map((h,i)=><a key={h} href={`#${slugify(h)}`}><span>{String(i+1).padStart(2,'0')}</span>{h}</a>)}</nav>;}
export function Breadcrumb({items}:{items:{label:string;href?:string}[]}){return <nav aria-label="Breadcrumb" className="breadcrumb"><Link href="/">Home</Link>{items.map(i=><span key={i.label}><span aria-hidden="true">/</span>{i.href?<Link href={i.href}>{i.label}</Link>:i.label}</span>)}</nav>;}
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>;}
