import {notFound} from 'next/navigation';
import Link from 'next/link';
import {Calculator} from '@/components/calculator';
import {calculatorInfo,type CalculatorKind} from '@/data/calculators';
import {PageIntro,Breadcrumb,FAQ} from '@/components/ui';
import {metadata} from '@/lib/site';
export function generateStaticParams(){return Object.keys(calculatorInfo).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const t=calculatorInfo[slug as CalculatorKind];return t?metadata(t.name,t.description,slug==='revpar-calculator'?'/revpar-calculator':`/tools/${slug}`):{};}
export default async function Tool({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const kind=slug as CalculatorKind;const t=calculatorInfo[kind];if(!t)notFound();const formula=kind==='ota-commission-calculator'?'Monthly OTA revenue × commission rate. Annual cost assumes the same revenue and rate for all 12 months.':kind==='direct-booking-savings-calculator'?'Current direct share = 100% − OTA share. Shift = maximum of zero and (target direct share − current direct share). Annual savings = monthly revenue × shift × commission rate × 12.':kind==='occupancy-calculator'?'Occupancy = room nights sold ÷ room nights available × 100.':kind==='adr-calculator'?'ADR = room revenue ÷ room nights sold.':'RevPAR = room revenue ÷ room nights available.';return <div className="page-content"><Breadcrumb items={[{label:'Tools',href:'/tools'},{label:t.name}]}/><PageIntro eyebrow="A LITTLE FINANCIAL CLARITY" title={t.name}>{t.description}</PageIntro>{kind==='revpar-calculator'?<div className="callout"><span className="eyebrow">NEW IN-DEPTH RESOURCE</span><p>Use the expanded <Link href="/revpar-calculator">RevPAR calculator and hotel guide</Link> for currency options, both calculation methods, examples, and RevPAR Index guidance.</p></div>:<Calculator kind={kind}/>}<div className="prose narrow section"><h2>What’s behind the numbers?</h2><p>{formula}</p>{kind==='direct-booking-savings-calculator'&&<p>This simplified model assumes all revenue is either OTA or direct, total revenue stays constant, and the displaced OTA bookings carry the same average commission. It excludes changes in room rates, occupancy, payment fees, website costs and marketing spend. Percentages refer to revenue, not reservation counts.</p>}{kind==='ota-commission-calculator'&&<p>For example, $10,000 in monthly OTA booking revenue at 15% commission gives $1,500 in monthly commissions and $18,000 over a constant 12-month period. Actual agreements may include additional fees or a different commission base.</p>}<FAQ items={[{question:'Do you save my numbers?',answer:'No. These calculations happen in your browser. Values reset when you reload the page.'},{question:'Which currency should I use?',answer:'Monetary results are labeled USD. Convert your figures to USD first and use the same basis throughout.'},{question:'Can I use these figures for a business decision?',answer:'Use them as an initial estimate. Validate your actual contracts, reporting definitions, seasonal revenue and other costs before making a decision.'}]}/><Link className="text-link" href="/tools">← Explore all calculators</Link></div></div>;}

