import Link from 'next/link';
import {notFound} from 'next/navigation';
import {comparisonSections,slugify} from '@/data/software';
import {Breadcrumb,PageIntro,SampleNotice,Toc,ComparisonTable} from '@/components/ui';
import {metadata as makeMetadata} from '@/lib/site';
export function generateStaticParams(){return [{slug:'lodgify-vs-hostaway'}];}
export const metadata=makeMetadata('Lodgify vs Hostaway: a comparison framework','Compare operational requirements, costs and property fit with a transparent sample research framework.','/comparisons/lodgify-vs-hostaway');
const questions:Record<string,string>={Pricing:'Request a like-for-like quote including onboarding, transaction fees, tax and renewal terms. Compare the same property count and billing period.',PMS:'Demonstrate arrivals, room allocation, modifications and cancellations using your real inventory structure.','Channel Management':'Confirm each OTA, connection type, room mapping and failure notification process.','Booking Engine':'Complete a mobile booking, amend it and process a cancellation. Check local currencies and payment methods.','Direct Booking Website':'Check editing controls, domain ownership, accessibility, site portability and booking integration.',Automation:'Trace each trigger, exception and manual override. Check who is alerted when a step fails.','Guest Messaging':'Verify actual messaging channels, shared access, delivery status and a clear handoff to staff.',Payments:'Check supported countries, settlement times, refund fees and who handles disputes.',Reporting:'Request usable exports for revenue, occupancy, cancellations and taxes. Compare reporting definitions.','Mobile Experience':'Try an arrival, a booking modification and an urgent message on the phone your team uses.',Support:'Ask for support hours, response targets, onboarding scope and escalation options in your time zone.',Integrations:'Confirm the exact integration and data direction, ownership of support, and any extra subscription.','Best By Property Size':'Model your current inventory and the next stage of growth. Check pricing thresholds and permissions.','Final Considerations':'Keep unresolved questions visible. Ask for written confirmation of every requirement that would stop your team from operating.',Alternatives:'Include your current setup, separate specialist tools and other integrated platforms in the shortlist. A new system should justify migration effort.'};
export default async function Comparison({params}:{params:Promise<{slug:string}>}){if((await params).slug!=='lodgify-vs-hostaway')notFound();return <div className="page-content"><Breadcrumb items={[{label:'Comparisons',href:'/comparisons'},{label:'Lodgify vs Hostaway'}]}/><PageIntro eyebrow="THE WORKFLOW COMPARISON" title="Lodgify vs Hostaway">Different properties need different answers. Use this side-by-side framework to prepare for a more useful demo.</PageIntro><div className="comparison-banner"><span><i className="product-mark lodgify">L</i>Lodgify</span><em>vs.</em><span><i className="product-mark hostaway">H</i>Hostaway</span></div><SampleNotice/><div className="reading-layout"><article className="prose"><section><h2>Quick recommendation by use case</h2><p>No winners have been assigned. These example evaluation priorities show how we intend to organize verified recommendations.</p><div className="use-case-grid">{[['Solo host','Setup effort and routine guest messages'],['5-room guesthouse','Room inventory and daily arrivals'],['10-property manager','Team permissions and location visibility'],['Direct-booking-focused business','Website journey and booking conversion'],['Airbnb-heavy operator','Messaging and reservation sync'],['Multi-OTA operator','Channel mapping and exception handling']].map(([type,focus])=><div key={type}><span className="eyebrow muted">EXAMPLE EVALUATION</span><h3>{type}</h3><p>{focus}</p><span className="tag">Verdict pending research</span></div>)}</div></section>{comparisonSections.map(h=><section id={slugify(h)} key={h}><h2>{h}</h2><p>{questions[h]}</p>{!['Final Considerations','Alternatives'].includes(h)&&<ComparisonTable headers={['Evaluation','Lodgify','Hostaway']} rows={[[h,'Not verified — ask in demo','Not verified — ask in demo'],['Evidence needed','Dated documentation or hands-on access','Dated documentation or hands-on access']]}/>}</section>)}<div className="article-end"><h3>Take the questions into your shortlist.</h3><p><Link href="/software/lodgify">Lodgify profile →</Link> &nbsp; <Link href="/software/hostaway">Hostaway profile →</Link></p></div></article><aside className="reading-sidebar"><Toc headings={comparisonSections}/></aside></div></div>;}
